import "./globals.css";
import Navbar from '@/components/Navbar.jsx'

export const metadata = {
  title: "CRUD APP",
  description: "Generated by Isaac",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
